# Generated by Django 4.1.7 on 2023-03-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WfmActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityid', models.CharField(db_column='Id', max_length=16)),
                ('datecreated', models.DateTimeField(blank=True, db_column='DateCreated', null=True)),
                ('agentlist', models.CharField(blank=True, db_column='AgentList', max_length=3000, null=True)),
                ('activity', models.CharField(blank=True, db_column='Activity', max_length=150, null=True)),
                ('connid', models.CharField(blank=True, db_column='ConnID', max_length=50, null=True)),
                ('loop', models.IntegerField(blank=True, db_column='Loop', null=True)),
                ('interactionid', models.CharField(blank=True, db_column='InteractionId', max_length=20, null=True)),
                ('mediatype', models.CharField(blank=True, db_column='MediaType', max_length=50, null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=50, null=True)),
                ('cutoff', models.IntegerField(db_column='Cutoff', null=True)),
            ],
            options={
                'db_table': 'WFM_Activity',
                'managed': False,
            },
        ),
    ]
